POST /api/rewards/allRewards HTTP/1.1
Host: localhost:8080
Content-Type: application/json

[
  {
    "customerId": 1,
    "firstName": "Ramsey",
    "lastName": "Arens",
    "months": [
      {
        "purchases": [
          "$256.80",
          "$3143.29",
          "$8130.52",
          "$4160.56",
          "$3888.87",
          "$1930.27",
          "$4324.76",
          "$1826.52",
          "$7318.57",
          "$9054.24",
          "$5587.89",
          "$3162.02",
          "$48.26",
          "$9602.67",
          "$6380.91",
          "$4493.75",
          "$6259.47",
          "$4663.56",
          "$9954.90",
          "$8937.67",
          "$6606.92",
          "$6960.71",
          "$4114.41",
          "$7687.85"
        ]
      },
      {
        "purchases": [
          "$7587.32",
          "$8169.56",
          "$6889.64",
          "$5820.40",
          "$7333.54",
          "$572.55",
          "$4154.85",
          "$1316.13",
          "$8232.81",
          "$3215.20",
          "$124.88",
          "$6857.25",
          "$5078.69",
          "$2107.76",
          "$8436.38",
          "$5651.16",
          "$3749.73",
          "$3514.25",
          "$9113.48",
          "$7918.36",
          "$5119.72",
          "$104.82",
          "$156.11",
          "$6347.20",
          "$1622.21",
          "$9115.58",
          "$4358.45",
          "$5010.73",
          "$9161.97",
          "$5348.84",
          "$2861.46",
          "$9734.78"
        ]
      },
      {
        "purchases": [
          "$339.40",
          "$2922.05",
          "$8051.55",
          "$8160.03",
          "$5072.11",
          "$6776.30",
          "$10.63",
          "$7704.80",
          "$8163.27",
          "$2185.99",
          "$6898.92",
          "$9700.72",
          "$7869.85",
          "$3076.46",
          "$966.25",
          "$796.97",
          "$2474.15",
          "$1804.75",
          "$3896.40",
          "$4646.78",
          "$7868.97",
          "$2984.81",
          "$2511.22",
          "$6989.63"
        ]
      }
    ]
  },
  {
    "customerId": 2,
    "firstName": "Jaimie",
    "lastName": "Heazel",
    "months": [
      {
        "purchases": [
          "$1687.55",
          "$7905.88",
          "$6202.78",
          "$7056.54",
          "$6930.08",
          "$9982.08",
          "$9628.78",
          "$3922.22",
          "$6170.74",
          "$712.83",
          "$5890.36",
          "$9516.72",
          "$7069.24",
          "$2542.79",
          "$1823.62",
          "$7118.12",
          "$5122.72",
          "$7094.05",
          "$6101.65",
          "$6098.26"
        ]
      },
      {
        "purchases": [
          "$2150.77",
          "$1979.79",
          "$7017.63",
          "$5564.88",
          "$4597.61",
          "$8272.98",
          "$42.47",
          "$3777.24",
          "$2081.00",
          "$6149.40",
          "$1568.43",
          "$3217.30",
          "$9243.68",
          "$672.14",
          "$5329.11",
          "$4755.18",
          "$1634.93",
          "$921.54",
          "$4068.75",
          "$2901.35",
          "$7800.59",
          "$7003.14",
          "$8943.58",
          "$8105.08",
          "$2118.37",
          "$6929.81",
          "$716.70",
          "$3844.02",
          "$4717.87",
          "$6420.01",
          "$4506.28",
          "$8248.51"
        ]
      },
      {
        "purchases": [
          "$1813.45",
          "$9366.42",
          "$190.16",
          "$5503.65",
          "$5495.96",
          "$4284.48",
          "$8044.54",
          "$6440.53",
          "$4395.89",
          "$7033.82",
          "$8762.92",
          "$8668.07",
          "$9113.27",
          "$3241.38",
          "$8520.01",
          "$9015.51",
          "$2555.17",
          "$9334.41",
          "$1277.22",
          "$1067.42",
          "$5279.55",
          "$7728.91",
          "$9172.76",
          "$1081.64",
          "$2512.69",
          "$9593.92",
          "$7130.86",
          "$20.45"
        ]
      }
    ]
  },
  {
    "customerId": 3,
    "firstName": "Ingar",
    "lastName": "Hallihane",
    "months": [
      {
        "purchases": [
          "$1156.67",
          "$5059.97",
          "$4017.01",
          "$6198.28",
          "$9864.40",
          "$7324.25",
          "$1982.04",
          "$3925.75",
          "$4583.80",
          "$1186.59",
          "$5806.60",
          "$5415.03",
          "$7854.61",
          "$9534.02",
          "$6302.75",
          "$4686.20"
        ]
      },
      {
        "purchases": [
          "$5491.66",
          "$3285.11",
          "$659.71",
          "$9740.44",
          "$1377.74",
          "$1756.62",
          "$7374.52",
          "$7760.04",
          "$2413.97",
          "$6519.22",
          "$7132.46",
          "$31.05",
          "$9394.43",
          "$6878.05",
          "$8707.14",
          "$6161.70",
          "$8781.89",
          "$8235.09",
          "$4841.17",
          "$5928.04",
          "$1108.83",
          "$2829.96",
          "$6214.46",
          "$9935.09",
          "$5466.85",
          "$6933.13",
          "$3673.26",
          "$7208.57",
          "$2210.15",
          "$2058.30",
          "$2802.79",
          "$4568.73"
        ]
      },
      {
        "purchases": [
          "$7584.60",
          "$8182.88",
          "$2491.40",
          "$6597.41",
          "$3425.94",
          "$560.63",
          "$7637.42",
          "$219.42",
          "$5311.95",
          "$362.04",
          "$8145.38",
          "$6312.36",
          "$5306.21",
          "$9710.45",
          "$2077.06",
          "$7767.13",
          "$4812.72",
          "$6172.45",
          "$8516.71",
          "$1011.13",
          "$7342.49",
          "$9275.52",
          "$8761.83",
          "$294.23",
          "$6109.48",
          "$8252.22",
          "$1899.09",
          "$4024.23",
          "$454.55",
          "$7153.78",
          "$8746.90",
          "$72.52"
        ]
      }
    ]
  },
  {
    "customerId": 4,
    "firstName": "Roland",
    "lastName": "Lokier",
    "months": [
      {
        "purchases": [
          "$889.51",
          "$5796.26",
          "$7300.41",
          "$5514.16",
          "$4689.13",
          "$3643.53",
          "$8668.42",
          "$3911.58",
          "$3976.79",
          "$1097.69",
          "$1200.75",
          "$1821.83",
          "$1018.44",
          "$4878.56",
          "$5083.19",
          "$6533.45",
          "$5203.48",
          "$4739.32",
          "$7520.18",
          "$2114.28",
          "$4615.45",
          "$2290.14",
          "$5275.27",
          "$7279.56",
          "$6120.23",
          "$4612.07",
          "$3944.17",
          "$4097.54",
          "$1346.76",
          "$1061.39",
          "$2162.15",
          "$7521.43"
        ]
      },
      {
        "purchases": [
          "$1175.48",
          "$9493.29",
          "$8586.51",
          "$6621.67",
          "$1367.53",
          "$6059.74",
          "$3157.11",
          "$2279.56",
          "$4179.15",
          "$3853.12",
          "$9879.34",
          "$3305.72",
          "$4516.20",
          "$1940.00",
          "$9505.34",
          "$1473.92",
          "$4417.37",
          "$3596.36",
          "$6168.58",
          "$8809.38",
          "$1487.36",
          "$5079.41",
          "$7742.51",
          "$1972.38"
        ]
      },
      {
        "purchases": [
          "$3571.48",
          "$4928.08",
          "$9680.73",
          "$1851.01",
          "$5698.99",
          "$8038.09",
          "$2579.75",
          "$5952.12",
          "$5300.75",
          "$6525.09",
          "$2856.88",
          "$2858.30",
          "$521.45",
          "$1061.15",
          "$6757.33",
          "$6417.52",
          "$7769.66",
          "$8404.77",
          "$2244.25",
          "$3441.85",
          "$8303.10",
          "$8299.88",
          "$4436.70",
          "$4633.94"
        ]
      }
    ]
  },
  {
    "customerId": 5,
    "firstName": "Celinda",
    "lastName": "Hallede",
    "months": [
      {
        "purchases": [
          "$9820.35",
          "$7873.19",
          "$172.52",
          "$8375.42",
          "$2212.10",
          "$2820.77",
          "$811.38",
          "$7615.67",
          "$1782.58",
          "$7805.76",
          "$1027.47",
          "$5024.88"
        ]
      },
      {
        "purchases": [
          "$9779.13",
          "$5787.65",
          "$2635.19",
          "$4822.87",
          "$2151.33",
          "$3165.29",
          "$6757.85",
          "$2125.57",
          "$7016.47",
          "$4851.78",
          "$9004.84",
          "$876.58",
          "$4945.35",
          "$67.36",
          "$8958.35",
          "$2539.14",
          "$7617.60",
          "$736.80",
          "$8078.60",
          "$5437.39",
          "$8022.61",
          "$5229.49",
          "$6976.02",
          "$510.69",
          "$521.05",
          "$9634.81",
          "$975.45",
          "$728.16",
          "$8373.92",
          "$418.01",
          "$3112.48",
          "$8150.87"
        ]
      },
      {
        "purchases": [
          "$8125.22",
          "$8484.22",
          "$5695.26",
          "$6986.54",
          "$5910.28",
          "$9743.86",
          "$4740.54",
          "$3376.07",
          "$3852.81",
          "$3915.60",
          "$8373.62",
          "$3235.45",
          "$3167.99",
          "$8939.52",
          "$2424.82",
          "$1342.14",
          "$6952.56",
          "$5371.76",
          "$8470.52",
          "$4116.76",
          "$2627.31",
          "$4607.62",
          "$1986.77",
          "$4494.55",
          "$1247.24",
          "$1097.01",
          "$428.29",
          "$1798.67",
          "$678.02",
          "$760.54",
          "$7336.54",
          "$3137.40",
          "$3868.47",
          "$1695.57",
          "$9604.95",
          "$3955.69"
        ]
      }
    ]
  }
]